### ISSUE TITLE
Air Intake and Nozzle

### ISSUE THREAD

**Issue by l0k1** [NikolaiVChr/flightgear-viggen-masters#15]
Maybe more of a wishlist item, but changing the model to have a proper air intake, a better motor view from the back, and a nozzle would be nice.

Air intake:
![asdf](http://www.flevoaviationhobby.net/walkaround/aircraft/viggen_37901/1024/0006.jpg)

Nozzle/Motor 1:
![asdf](http://www.aircraftresourcecenter.com/awa01/101-200/awa200-viggen/part2/images_Niklas_Knutzen/ja_rear.jpg)

Nozzle/Motor 2:
![asdf](http://www.aircraftresourcecenter.com/awa01/501-600/awa519-Viggen-Toll/41.jpg)

As the SK-37 is being built off of the JA-37 fuselage, this might have to come first for me. Also, it'd be a big quality improvement.

**Comment by l0k1** [comment]
Initial work on the air intake - still needs a little bit of cleaning, and the engine front needs texturing.

![asdf](https://i.imgur.com/FmuZrm1.png)
![asdf](https://i.imgur.com/pF6SDfW.png)

**Comment by NikolaiVChr** [comment]
Nice!

**Comment by l0k1** [comment]
Rear engine + nozzle, ready for mats and textures.
![asdf](https://i.imgur.com/P9OLMkI.png)

**Comment by l0k1** [comment]
More pictures.
![asdf](http://scontent.cdninstagram.com/t51.2885-15/s750x750/sh0.08/e35/12338916_925221097592134_1826649407_n.jpg?ig_cache_key=MTE0OTk3NzUzMzUyOTE4NTI3NA%3D%3D.2)
![asdf](http://scontent.cdninstagram.com/t51.2885-15/s750x750/sh0.08/e35/12331677_948970631815709_971564699_n.jpg?ig_cache_key=MTEzMzM3NjEwNjM5NjYzNzMyMQ%3D%3D.2)
![asdf](http://scontent.cdninstagram.com/t51.2885-15/s750x750/sh0.08/e35/12093727_731574960319664_1606455739_n.jpg?ig_cache_key=MTA5MzkyNzUyODY1MTIxNTAxNg%3D%3D.2)
![asdf](http://scontent.cdninstagram.com/t51.2885-15/s750x750/sh0.08/e35/10809709_1671038366487131_1159770827_n.jpg?ig_cache_key=MTE1MTIzMDE1NTU5MTk2MzAzMw%3D%3D.2)

**Comment by l0k1** [comment]
Modelling/texturing is done
![asdf](https://i.imgur.com/ui0MEvx.png)
![asdf](https://i.imgur.com/MICKScf.png)

**Comment by NikolaiVChr** [comment]
awesome

**Comment by NikolaiVChr** [comment]
Damn you Pinto! Now I keep throttling up and down in model view, just to see the engine animations.
This is simply fantastic.
