### ISSUE TITLE
Outdated altimeter models

### ISSUE THREAD

**Issue by colingeniet** [NikolaiVChr/flightgear-viggen-masters#21]
The altimeter models (and maybe some others, I did not check) seem to be missing the changes corresponding to this commit
https://github.com/NikolaiVChr/flightgear-saab-ja-37-viggen/commit/640c39463963f679fafb04eefa3cae261e85eebe
Do you have the corresponding blender files by any chance ?

**Comment by NikolaiVChr** [comment]
I have been lazy of late and just imported the AC3D into blender directly, made the edits and converted them back out, and then maybe hand edited the materials. So I skipped the step of using the blender models from/to this repo.
Only thing that is really kept uptodate in this repo is the main aircraft model (second last change in this repo, the last change by pinto with more variants had the model cut up, which lead to broken smooth shading in FG so its not used, has to be stitched together first again).

**Comment by colingeniet** [comment]
Thank you, I'll do the same in that case
